test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.99875e2b4c69f9ef22b05f565eeab52a8befb566.name = "Upgrade from 1.979~ynh2"
